<?php
declare(strict_types=1);

namespace Tests\Postgres;

use Fyre\Cache\Cache;
use Fyre\Cache\Handlers\FileCacher;
use Fyre\DB\Connection;
use Fyre\DB\ConnectionManager;
use Fyre\DB\Handlers\Postgres\PostgresConnection;
use Fyre\FileSystem\Folder;
use Fyre\Schema\Schema;
use Fyre\Schema\SchemaRegistry;

use function getenv;

trait PostgresConnectionTrait
{
    protected Connection $db;

    protected Schema $schema;

    public static function setUpBeforeClass(): void
    {
        ConnectionManager::clear();
        Cache::clear();

        ConnectionManager::setConfig([
            'default' => [
                'className' => PostgresConnection::class,
                'host' => getenv('POSTGRES_HOST'),
                'username' => getenv('POSTGRES_USERNAME'),
                'password' => getenv('POSTGRES_PASSWORD'),
                'database' => getenv('POSTGRES_DATABASE'),
                'port' => getenv('POSTGRES_PORT'),
                'charset' => 'utf8',
                'persist' => true,
            ],
        ]);

        Cache::setConfig([
            'schema' => [
                'className' => FileCacher::class,
                'path' => 'tmp',
                'prefix' => 'schema.',
                'expire' => 3600,
            ],
        ]);

        $cache = Cache::use('schema');

        SchemaRegistry::setCache($cache);

        $connection = ConnectionManager::use();

        $connection->query('DROP TABLE IF EXISTS test_values');
        $connection->query('DROP TABLE IF EXISTS test');

        $connection->query(<<<'EOT'
            CREATE TABLE test (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                name CHARACTER VARYING(255) NULL DEFAULT NULL,
                value DOUBLE PRECISION NOT NULL DEFAULT 5,
                price NUMERIC(10,2) NOT NULL DEFAULT 2.50,
                text CHARACTER VARYING(255) NOT NULL DEFAULT 'default',
                bool BOOLEAN NOT NULL DEFAULT FALSE,
                date_precision TIMESTAMP(0) NULL DEFAULT NULL,
                created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                modified TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id)
            )
        EOT);
        $connection->query(<<<'EOT'
            CREATE UNIQUE INDEX name ON test (name)
        EOT);
        $connection->query(<<<'EOT'
            CREATE INDEX name_value ON test (name, value)
        EOT);
        $connection->query(<<<'EOT'
            CREATE TABLE test_values (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                test_id INTEGER NOT NULL DEFAULT '0',
                value INTEGER NOT NULL,
                PRIMARY KEY (id)
            )
        EOT);
        $connection->query(<<<'EOT'
            CREATE INDEX test_values_test_id ON test_values (test_id)
        EOT);
        $connection->query(<<<'EOT'
            CREATE INDEX value ON test_values (value)
        EOT);
        $connection->query(<<<'EOT'
            ALTER TABLE test_values ADD CONSTRAINT test_values_test_id FOREIGN KEY (test_id) REFERENCES public.test (id) ON UPDATE CASCADE ON DELETE CASCADE
        EOT);
    }

    public static function tearDownAfterClass(): void
    {
        $folder = new Folder('tmp');

        if ($folder->exists()) {
            $folder->delete();
        }

        $connection = ConnectionManager::use();
        $connection->query('DROP TABLE IF EXISTS test_values');
        $connection->query('DROP TABLE IF EXISTS test');
    }

    protected function setUp(): void
    {
        $this->db = ConnectionManager::use();
        $this->schema = SchemaRegistry::getSchema($this->db);
    }
}
